// Global
export const EVENT_ON_LOADED = 'wazo/ON_LOADED';
export const EVENT_APP_UNLOADED = 'wazo/EVENT_APP_UNLOADED';
export const EVENT_PLUGIN_UNLOADED = 'wazo/EVENT_PLUGIN_UNLOADED';
export const EVENT_APP_INITIALIZE = 'wazo/EVENT_APP_INITIALIZE';
export const EVENT_ON_LOGOUT = 'wazo/EVENT_ON_LOGOUT';
export const EVENT_SEND_IFRAME_MESSAGE = 'wazo/EVENT_SEND_IFRAME_MESSAGE';
export const EVENT_SEND_BACKGROUND_MESSAGE = 'wazo/EVENT_SEND_BACKGROUND_MESSAGE';
export const EVENT_ON_IFRAME_MESSAGE = 'wazo/EVENT_ON_IFRAME_MESSAGE';
export const EVENT_ON_BACKGROUND_MESSAGE = 'wazo/EVENT_ON_BACKGROUND_MESSAGE';

// WDA
export const EVENT_CLOSE_LEFT_PANEL = 'wazo/EVENT_CLOSE_LEFT_PANEL';
export const EVENT_OPEN_LEFT_PANEL = 'wazo/EVENT_OPEN_LEFT_PANEL';
export const EVENT_START_CALL = 'wazo/START_CALL';
export const EVENT_ON_CALL_INCOMING = 'wazo/EVENT_ON_CALL_INCOMING';
export const EVENT_ON_CALL_MADE = 'wazo/EVENT_ON_CALL_MADE';
export const EVENT_ON_CALL_ANSWERED = 'wazo/EVENT_ON_CALL_ANSWERED';
export const EVENT_ON_CALL_ACCEPTED = 'wazo/EVENT_ON_CALL_ACCEPTED';
export const EVENT_ON_CALL_HUNG_UP = 'wazo/EVENT_ON_CALL_HUNG_UP';
export const EVENT_OPEN_LINK = 'wazo/EVENT_OPEN_LINK';
export const EVENT_CREATE_MEETING = 'wazo/EVENT_CREATE_MEETING';
export const EVENT_OPEN_MEETING_LOBBY = 'wazo/EVENT_OPEN_MEETING_LOBBY';
export const EVENT_OPEN_SETTINGS = 'wazo/EVENT_OPEN_SETTINGS';
export const EVENT_ON_MEETING_CREATED = 'wazo/EVENT_ON_MEETING_CREATED';
export const EVENT_ROUTE_CHANGE = 'wazo/EVENT_ROUTE_CHANGE';
export const EVENT_WS_MESSAGE = 'wazo/EVENT_WS_MESSAGE';
export const EVENT_PLAY_PROGRESS_SOUND = 'wazo/EVENT_PLAY_PROGRESS_SOUND';
export const EVENT_PLAY_NEW_MESSAGE_SOUND = 'wazo/EVENT_PLAY_NEW_MESSAGE_SOUND';
export const EVENT_PLAY_INCOMING_CALL_SOUND = 'wazo/EVENT_PLAY_INCOMING_CALL_SOUND';
export const EVENT_PLAY_DOUBLE_CALL_SOUND = 'wazo/EVENT_PLAY_DOUBLE_CALL_SOUND';
export const EVENT_PLAY_HANGUP_SOUND = 'wazo/EVENT_PLAY_HANGUP_SOUND';
export const EVENT_STOP_CURRENT_SOUND = 'wazo/EVENT_STOP_CURRENT_SOUND';
export const EVENT_CONFIGURE_SOUNDS = 'wazo/EVENT_CONFIGURE_SOUNDS';
export const EVENT_RESET_SOUNDS = 'wazo/EVENT_RESET_SOUNDS';
export const EVENT_DISPLAY_NOTIFICATION = 'wazo/EVENT_DISPLAY_NOTIFICATION';
export const EVENT_CHANGE_NAVBAR_COLOR = 'wazo/EVENT_CHANGE_NAVBAR_COLOR';
export const EVENT_RESET_NAVBAR_COLOR = 'wazo/EVENT_RESET_NAVBAR_COLOR';
export const EVENT_DISPLAY_MODAL = 'wazo/EVENT_DISPLAY_MODAL';
export const EVENT_REMOVE_MODAL = 'wazo/EVENT_REMOVE_MODAL';
export const EVENT_USER_JOIN_ROOM = 'wazo/EVENT_USER_JOIN_ROOM';
export const EVENT_USER_LEAVE_ROOM = 'wazo/EVENT_USER_LEAVE_ROOM';
export const EVENT_PARTICIPANT_JOIN_ROOM = 'wazo/EVENT_PARTICIPANT_JOIN_ROOM';
export const EVENT_PARTICIPANT_LEAVE_ROOM = 'wazo/EVENT_PARTICIPANT_LEAVE_ROOM';
export const EVENT_IGNORE_CALL = 'wazo/EVENT_IGNORE_CALL';
export const EVENT_ON_NEW_SESSION = 'wazo/EVENT_ON_NEW_SESSION';
export const EVENT_UPDATE_BADGE = 'wazo/EVENT_UPDATE_BADGE';
export const EVENT_DISPLAY_BANNER = 'wazo/EVENT_DISPLAY_BANNER';
export const EVENT_REMOVE_BANNER = 'wazo/EVENT_REMOVE_BANNER';


// Portal
export const EVENT_ON_CONNECTED_TO_STACK = 'wazo/EVENT_ON_CONNECTED_TO_STACK';
export const EVENT_ON_SWITCH_STACK_TENANT = 'wazo/EVENT_ON_SWITCH_STACK_TENANT';
export const EVENT_CHANGE_TOOLBAR_DISPLAY = 'wazo/EVENT_CHANGE_TOOLBAR_DISPLAY';

// Mobile
export const EVENT_MOBILE_HEADER = 'wazo/mobile/EVENT_MOBILE_HEADER';
export const EVENT_MOBILE_CONTEXTUAL_MENU = 'wazo/mobile/EVENT_MOBILE_CONTEXTUAL_MENU';
export const EVENT_MOBILE_SHOW_BOTTOM_NAV = 'wazo/mobile/EVENT_MOBILE_SHOW_BOTTOM_NAV';
export const EVENT_MOBILE_ON_MENU_ACTION = 'wazo/mobile/EVENT_MOBILE_ON_MENU_ACTION';
export const EVENT_MOBILE_ON_HEADER_BACK = 'wazo/mobile/EVENT_MOBILE_ON_HEADER_BACK';
